name: Build Applications and Generate Installers

on:
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # o la versión que estés usando

      - name: Build Android App
        run: ./gradlew assembleRelease  # Comando para compilar tu aplicación Android

      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: app/build/outputs/apk/release/app-release.apk

  build-desktop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Build Desktop App
        run: mvn clean package  # Comando para compilar tu aplicación de escritorio

      - name: Upload Desktop Installer
        uses: actions/upload-artifact@v3
        with:
          name: desktop-installer
          path: target/desktop-app.jar
